baseURL = "https://anony6174.github.io/d1ff/"
languageCode = 'en-us'
title = "d1ff"
theme = "FixIt"
ignoreLogs = ['warning-dev-version']

canonifyURLs = true



[markup]
  _merge = "shallow"

[taxonomies]
  _merge = "shallow"  
  archive = "archives"
[imaging]
  anchor = 'Center'

[outputs]
  _merge = "shallow"
  home = ["HTML", "RSS", "JSON"]  
  section = ["HTML"]
  taxonomy = ["HTML"]



  

[params]
  
  [params.author]
    name = "_d1ff"
    avatar = "/images/me.jpg"
    email = "helloyou2520@gmail.com"
    link = "https://github.com/Anony6174/"
  
  [params.social]
    github = "Anony6174"
    twitter = "Anuj1337"

  [params.recentlyUpdated]
    archives = true
    section = true
    list = true
    days = 30
    maxCount = 10
  
  # FOOTER customization
  [params.footer]
    enable = false
    customText = "© 2025 d1ff. All rights reserved."
    hugo = false
    theme = true
  



  


  [params.plugins]
    [params.plugins.fontawesome]
      enable = true 
  
  

  # Site appearance
  defaultTheme = "dark"         # 'light', 'dark', or 'auto'
  dateFormat = "Jan 2, 2006"    # Customize date format
  colorScheme = "auto"



  [params.assets]
    customCSS = ["css/_custom.scss"]  

  
  
  enableInlineShortcodes = true
  [params.page]
    home = { enable = true }
    showMeta = true            # show date, author, tags, etc.
    showTags = true            # specifically show tags
    showCategories = true      # show categories too (optional)
    


  [params.archives]
    paginate = 20
    dateFormat = "01-02"

  [params.home]
    paginate = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/d1ff/images/me.jpg"
      avatarMenu = ""
      title = "d1ff"
      subtitle = "Every fix is temporary. Every bug is eternal."
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = false
      
  
  [params.readingProgress]
    enable = true
    start = "left"
    position = "top"
    reversed = false
    light = "#FFA500"  # black for light theme
    dark = "#777777"   # white for dark theme
    height = "3px"
  
  [params.header]
    desktopMode = "sticky"
    mobileMode = "auto"
    [params.header.title]
      logo = "/d1ff/images/me.jpg"
      name = ""
      pre = ""
      post = ""
      typeit = false
    [params.header.subtitle]
      name = ""
      typeit = false
  
  [params.image]
    cacheRemote = true
    optimise = true

  mainSectionPages = ["posts"]  

[caches]
  [caches.images]
    dir = ':cacheDir/images'  


[menu]
  [[menu.main]]
    identifier = "archives"
    parent = ""
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Archives"
    url = "/archives/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
    # FixIt 0.2.14 | NEW add user-defined content to menu items
    [menu.main.params]
      # add css class to a specific menu item
      class = ""
      # whether set as a draft menu item whose function is similar to a draft post/page
      draft = false
      # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
      icon = "fa-solid fa-archive"
      # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
      type = ""
      # FixIt 0.3.9 | NEW whether to show the submenu item divider line
      divided = false
  [[menu.main]]
    identifier = "categories"
    parent = ""
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
  [[menu.main]]
    identifier = "tags"
    parent = ""
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"    
  